### PR TITLE
Improve auto background changer

### PR DESCRIPTION
**Pull request by pauliax**

### CODE REVIEW

**Comment by pauliax** [comment]
related to #26

**Comment by AmitGujar** [comment]
Remove change minutes input from index.html because we are not allowing the user to set the limit for background wallpaper change. The limit for Auto wallpaper change should be predefined in main.js.

**Comment by pauliax** [comment]
Removed

**Comment by AmitGujar** [comment]
I see you didn't make any changes in code in order to fix the issue.

**Pull request closed without merging**
