### PR TITLE
Enhancement - Add Todo Section

### LINKED ISSUE #12: Add Todo Section
**Todo Section**
Add the todo section in the bottom right section.

**Features Required**
Once the task has been completed, allow the user to mark the task as completed.
Allow users to delete the todo list.

**Screenshot**
Screenshot 2020-10-04 003856

### PR DESCRIPTION
**Pull request by MKPATH2015**
Inprogress Issue #12

Check the UI work. **Just wanted to see if you are okay with initial changes**

### CODE REVIEW

**Comment by AmitGujar** [comment]
UI looks perfect.

**Comment by AmitGujar** [comment]
Could you add an option for the user to delete/clear all todos? or you can add auto-clear the todo once the user marked specific todo as complete.

- todo list gets reset after the browser is closed, it should be persistent until the user deletes current tasks.

**Comment by MKPATH2015** [comment]
Added delete option to delete all the Todos. Deleting a Todo on marking done, didn't seem like a good way to me.

**Comment by MKPATH2015** [comment]
Logic to persist the data is yet to be implemented

**Comment by AmitGujar** [comment]
Ok, the current changes are nice and once you added that persist data then pr will be merged, now I will remove other guy from this issue.

**Pull request merged**
