### PR TITLE
Replaced the text button into icon button

### LINKED ISSUE #3: Replace text button to icon.
**Description**
Change ME button allows users to change the background manually, Change that button to the Refresh/Reload icon.

Screenshot (29)

Expected Changes - 
- Only icon (not icon + text).
- Icon background must be transparent.
- Animated icon will be appreciated.

### PR DESCRIPTION
**Pull request by vandana1499**
#3 
Replaced the text button icon button

### CODE REVIEW

**Comment by AmitGujar** [comment]
Looks fine, I will wait for the other two guys to add then I will merge the best of three.

**Review by Abdul-Sen — COMMENTED** [review]
This is great! I would just like to suggest an enhancement to add minimal animation by adding the following to `style.css`
```css
#change-btn:hover i {
  animation: fa-spin 0.5s linear;
}

#change-btn:active {
  color: grey;
}
```
After this your button would look something like this:

</img>

**Comment by vandana1499** [comment]
@Abdul-Sen , Yes it looks great now!

**Comment by AmitGujar** [comment]
@vandana1499, @Abdul-Sen  looks perfect, just make that refresh icon a bit large and make it's background transparent.

**Pull request merged**
