### PR TITLE
FIXED BUG:Resolution lesser than 1080p fail to load all contents.

### PR DESCRIPTION
**Pull request by M4yankChoudhary**
Fixed Screens with a resolution lesser than 1080p fail to load all contents of the extension. #15

### CODE REVIEW

**Comment by M4yankChoudhary** [comment]
#15

**Comment by AmitGujar** [comment]
Seems like you didn't implement the grid properly, a lot of white space is there which makes content alignment of time and search looks off.

Take a look at these screenshots.
Screenshot 2020-10-07 110052

Screenshot 2020-10-07 110132

**Comment by M4yankChoudhary** [comment]
Made changes.

**Comment by AmitGujar** [comment]
Increase the space between time and search.
Screenshot 2020-10-07 133922

try to keep it like this
Screenshot 2020-10-07 134141

Try using values in % for time instead of px.

**Comment by M4yankChoudhary** [comment]
Thanks!

**Pull request merged**
