### PR TITLE
Added top visited sites to main navbar

### LINKED ISSUE #7: Add top visited sites.
**Description**
Replace current links in the navbar of extension to most visited sites.

**Screenshot**
Screenshot 2020-09-30 130210

**This API will help**
https://developer.chrome.com/extensions/topSites

### PR DESCRIPTION
**Pull request by nicosh**
Added top visited sites (first 7) to main navbar, if site name is too long it will be splitted

### CODE REVIEW

**Comment by AmitGujar** [comment]
There is an error.
Screenshot 2020-09-30 200259

**Comment by nicosh** [comment]
Should be fixed now

**Comment by AmitGujar** [comment]
Still getting the same error
Screenshot 2020-09-30 204805

I would suggest you run the extension in your browser, you will see the error.

**Comment by nicosh** [comment]
if i run  in my browser i dont see any error. 
can you post here what `console.log(urls)` outputs in your browser? it seems that some websites doesnt have the title attribute...

**Comment by AmitGujar** [comment]
To see extension error in the browser, go to the extensions menu and you will find three options (details, remove, error), check error there.

Screenshot 2020-09-30 222206

**Comment by nicosh** [comment]
yes what i mean is that extension works fine in my browser, seems that your top websites list contains some invalid websites (no name or title) can you check if now is fixed?

**Comment by AmitGujar** [comment]
Nice.....!!! No errors this time.

**Pull request merged**
